//! Definition of the types of memory regions/capabilities that are granted
//! to the entry of the runtime.
//!
//! These are used to reduce the need of unsafe Rust to create capabilities out
//! of DDC while keeping track of the exact memory that the program has access
//! to while in safe Rust.

#[cfg(all(target_arch = "aarch64", target_abi = "purecap"))]
use cheri::prelude::*;
#[cfg(all(target_arch = "aarch64", target_abi = "purecap"))]
use cheri::ptr::Perms;

/// Unsafe traits implemented by MMIO register definitions
pub unsafe trait MmioGrant {}

/// Definition of a MMIO region granted to the application
pub struct Mmio<const ADDRESS: usize, T: MmioGrant>(core::marker::PhantomData<T>);

impl<const ADDRESS: usize, T: MmioGrant> Mmio<ADDRESS, T> {
    /// # Safety
    ///
    /// Only meant to be called by the code generated by the `entry` macro.
    #[doc(hidden)]
    pub const unsafe fn new() -> Self {
        Self(core::marker::PhantomData)
    }
}

/// Definition of the heap region granted to the application. This specifies the length
/// of the heap arena. The address of where the heap lies should be specified inside the linker
/// script.
pub struct Heap<const SIZE: usize>(());

impl<const SIZE: usize> Heap<SIZE> {
    /// # Safety
    ///
    /// Only meant to be called by the code generated by the `entry` macro.
    #[doc(hidden)]
    pub const unsafe fn new() -> Self {
        Self(())
    }
}

/// Object types range the application has access to through the granted sealing capability.
/// The grant hands over one sealing capability that has the bounds set to the `START` and `END` values.
pub struct SealRange<const START: usize, const END: usize>(());

impl<const START: usize, const END: usize> SealRange<START, END> {
    /// # Safety
    ///
    /// Only meant to be called by the code generated by the `entry` macro.
    #[doc(hidden)]
    pub const unsafe fn new() -> Self {
        Self(())
    }
}

#[cfg(all(target_arch = "aarch64", target_abi = "purecap"))]
impl<const ADDRESS: usize, T: MmioGrant + Sized> From<Mmio<ADDRESS, T>> for *mut T {
    fn from(_: Mmio<ADDRESS, T>) -> Self {
        let keep = Perms::GLOBAL | Perms::LOAD | Perms::STORE;
        cheri::ptr::default_data_mut::<u8>()
            .with_address(ADDRESS)
            .with_bounds(core::mem::size_of::<T>())
            .with_perms_clear_except(keep) as *mut T
    }
}

#[cfg(not(all(target_arch = "aarch64", target_abi = "purecap")))]
impl<const ADDRESS: usize, T: MmioGrant + Sized> From<Mmio<ADDRESS, T>> for *mut T {
    fn from(_: Mmio<ADDRESS, T>) -> Self {
        unimplemented!("grants can only be derived on the purecap target")
    }
}

#[cfg(all(target_arch = "aarch64", target_abi = "purecap"))]
impl<const SIZE: usize> From<Heap<SIZE>> for *mut u8 {
    fn from(_: Heap<SIZE>) -> Self {
        extern "C" {
            static __el1_heap_start: u8;
        }
        let keep = Perms::GLOBAL
            | Perms::LOAD
            | Perms::STORE
            | Perms::LOAD_CAPABILITY
            | Perms::STORE_CAPABILITY
            | Perms::STORE_LOCAL;

        // SAFETY: only the address of the linker symbol is taken, never its value
        let start = unsafe { core::ptr::addr_of!(__el1_heap_start) } as usize;

        cheri::ptr::default_data_mut::<u8>()
            .with_address(start)
            .with_bounds(SIZE)
            .with_perms_clear_except(keep)
    }
}

#[cfg(not(all(target_arch = "aarch64", target_abi = "purecap")))]
impl<const SIZE: usize> From<Heap<SIZE>> for *mut u8 {
    fn from(_: Heap<SIZE>) -> Self {
        unimplemented!("grants can only be derived on the purecap target")
    }
}
