//! Definition of the types of memory regions/capabilities that are granted
//! to the entry of the runtime.
//!
//! These are used to reduce the need of unsafe Rust to create capabilities out
//! of DDC while keeping track of the exact memory that the program has access
//! to while in safe Rust.

#[cfg(all(target_arch = "aarch64", target_abi = "purecap"))]
use cheri::prelude::*;
#[cfg(all(target_arch = "aarch64", target_abi = "purecap"))]
use cheri::ptr::Perms;

/// Definition of a MMIO region granted to the application
pub struct Mmio<const ADDRESS: usize, T>(core::marker::PhantomData<T>);

impl<const ADDRESS: usize, T> Mmio<ADDRESS, T> {
    /// # Safety
    ///
    /// Only meant to be called by the code generated by the `entry` macro.
    #[doc(hidden)]
    pub const unsafe fn new() -> Self {
        Self(core::marker::PhantomData)
    }
}

/// Definition of the heap region granted to the application. This specifies the length
/// of the heap arena. The address of where the heap lies should be specified inside the linker
/// script.
pub struct Heap<const SIZE: usize>(());

impl<const SIZE: usize> Heap<SIZE> {
    /// # Safety
    ///
    /// Only meant to be called by the code generated by the `entry` macro.
    #[doc(hidden)]
    pub const unsafe fn new() -> Self {
        Self(())
    }
}

/// Object types range the application has access to through the granted sealing capability.
/// The grant hands over one sealing capability that has the bounds set to the `START` and `END` values.
pub struct SealRange<const START: usize, const END: usize>(());

impl<const START: usize, const END: usize> SealRange<START, END> {
    /// # Safety
    ///
    /// Only meant to be called by the code generated by the `entry` macro.
    #[doc(hidden)]
    pub const unsafe fn new() -> Self {
        Self(())
    }
}

#[cfg(all(target_arch = "aarch64", target_abi = "purecap"))]
impl<const ADDRESS: usize, T: Sized> From<Mmio<ADDRESS, T>> for *mut T {
    fn from(_: Mmio<ADDRESS, T>) -> Self {
        let keep = Perms::GLOBAL | Perms::LOAD | Perms::STORE;
        cheri::ptr::default_data_mut::<u8>()
            .with_addr(ADDRESS)
            .with_bounds(core::mem::size_of::<T>())
            .with_perms_clear_except(keep) as *mut T
    }
}

#[cfg(not(all(target_arch = "aarch64", target_abi = "purecap")))]
impl<const ADDRESS: usize, T: Sized> From<Mmio<ADDRESS, T>> for *mut T {
    fn from(_: Mmio<ADDRESS, T>) -> Self {
        unimplemented!("grants can only be derived on the purecap target")
    }
}

#[cfg(all(target_arch = "aarch64", target_abi = "purecap"))]
impl<const SIZE: usize> From<Heap<SIZE>> for *mut u8 {
    fn from(_: Heap<SIZE>) -> Self {
        let keep = Perms::GLOBAL
            | Perms::LOAD
            | Perms::STORE
            | Perms::LOAD_CAPABILITY
            | Perms::STORE_CAPABILITY
            | Perms::STORE_LOCAL;

        // The address of the linker symbol is computed PC-relative. Referencing it as an
        // extern static would emit a capability relocation against a linker script symbol,
        // which crashes the Morello lld ("Bad section start symbol" assertion).
        let mut tmp: *mut u8;
        let start: usize;
        // SAFETY: only computes the address of the symbol
        unsafe {
            core::arch::asm!("adrp {cap:x}, __el1_heap_base", cap = out(reg) tmp, options(nomem, nostack, pure));
            core::arch::asm!("add {cap:x}, {cap:x}, :lo12:__el1_heap_base", cap = inout(reg) tmp, options(nomem, nostack, pure));
            core::arch::asm!("gcvalue {val:x}, {cap:x}", val = out(reg) start, cap = in(reg) tmp, options(nomem, nostack, pure));
        }

        cheri::ptr::default_data_mut::<u8>()
            .with_addr(start)
            .with_bounds(SIZE)
            .with_perms_clear_except(keep)
    }
}

#[cfg(not(all(target_arch = "aarch64", target_abi = "purecap")))]
impl<const SIZE: usize> From<Heap<SIZE>> for *mut u8 {
    fn from(_: Heap<SIZE>) -> Self {
        unimplemented!("grants can only be derived on the purecap target")
    }
}
