[package]
name = "aarch64-purecap-rt-macros"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Macros for the aarch64-purecap-rt runtime."
repository = "https://codeberg.org/irinanita/aarch64-purecap"
authors = ["Irina Nita <irina.nita@posteo.com>"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "=1.0.106"
quote = "=1.0.45"
syn = { version = "=2.0.117", features = ["extra-traits", "full"] }
